//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuConvert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuConvert.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute step tags are not supported. Use BPM + division notation such as &quot;(120){4}&quot;..
        /// </summary>
        public static string AbsoluteStepNotImplemented {
            get {
                return ResourceManager.GetString("AbsoluteStepNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MuConvert hit an internal error (AssertionFailed). Please report it at https://github.com/MuNet-OSS/MuConvert/issues . ({0}).
        /// </summary>
        public static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG:.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected modifier(s): {0}. They have been ignored..
        /// </summary>
        public static string ExtraModifiersIgnored {
            get {
                return ResourceManager.GetString("ExtraModifiersIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO:.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser and generator instances are single-use; do not call Parse or Generate more than once. Create a new instance for each chart..
        /// </summary>
        public static string InstanceMultipleUsage {
            get {
                return ResourceManager.GetString("InstanceMultipleUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key index (must be 1–8): {0}.
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid maidata file: no &apos;&amp;&apos; field markers were found..
        /// </summary>
        public static string InvalidMaidataFile {
            get {
                return ResourceManager.GetString("InvalidMaidataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid slide definition: {0}.
        /// </summary>
        public static string InvalidSlide {
            get {
                return ResourceManager.GetString("InvalidSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid touch area specifier: {0}.
        /// </summary>
        public static string InvalidTouchArea {
            get {
                return ResourceManager.GetString("InvalidTouchArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For multi-segment slides with per-segment durations, a wait-time fragment (e.g. {0.5##...}) may only appear on the first segment. Invalid wait-time markers were ignored..
        /// </summary>
        public static string InvalidWaitTime {
            get {
                return ResourceManager.GetString("InvalidWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string MessageAt {
            get {
                return ResourceManager.GetString("MessageAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}.
        /// </summary>
        public static string MessageLine {
            get {
                return ResourceManager.GetString("MessageLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parsing {0}.
        /// </summary>
        public static string MessageParsing {
            get {
                return ResourceManager.GetString("MessageParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar time {0:W}({1:F2}s).
        /// </summary>
        public static string MessageTime {
            get {
                return ResourceManager.GetString("MessageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot be set on Tap or Touch notes..
        /// </summary>
        public static string NoDuration {
            get {
                return ResourceManager.GetString("NoDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse simai syntax: .
        /// </summary>
        public static string SimaiGrammarFailed {
            get {
                return ResourceManager.GetString("SimaiGrammarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
