//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuConvert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuConvert.i18n.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart uses absolute time step notation like {0}. Support for this feature is experimental; if you run into issues, please report them at https://github.com/MuNet-OSS/MuConvert/issues..
        /// </summary>
        public static string AbsoluteStepUsed {
            get {
                return ResourceManager.GetString("AbsoluteStepUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simai parser error: {0}.
        /// </summary>
        public static string AntlrUnknownError {
            get {
                return ResourceManager.GetString("AntlrUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MuConvert hit an internal error (AssertionFailed). Please report it at https://github.com/MuNet-OSS/MuConvert/issues . ({0}).
        /// </summary>
        public static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart contains features not supported by MA2 1.03 (BreakEX). Those features were ignored and converted back to a pure break..
        /// </summary>
        public static string BreakExIn103 {
            get {
                return ResourceManager.GetString("BreakExIn103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart contains features not supported by MA2 1.03 (Break on Hold or Slide). Those features were ignored and converted back to the normal versions..
        /// </summary>
        public static string BreakHoldOrSlideIn103 {
            get {
                return ResourceManager.GetString("BreakHoldOrSlideIn103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart contains features not supported by MA2 1.03 (multi-segment connecting slides). Only the first slide segment was kept..
        /// </summary>
        public static string ConnectingSlideIn103 {
            get {
                return ResourceManager.GetString("ConnectingSlideIn103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG:.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart contains features not supported by MA2 (EX Slide). Those modifiers were ignored..
        /// </summary>
        public static string ExSlideIn105 {
            get {
                return ResourceManager.GetString("ExSlideIn105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You used multiple consecutive fake EACH ` symbols. This is not standard Simai syntax, but following the behavior of other charting tools, it is interpreted as two notes staggered further apart in time (each ` offsets timing by a 128th note). If this was not intentional, please review your input to avoid mistakes..
        /// </summary>
        public static string ExtenedFalseEach {
            get {
                return ResourceManager.GetString("ExtenedFalseEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected or redundant modifier(s): &apos;{0}&apos;. Ignored..
        /// </summary>
        public static string ExtraModifiersIgnored {
            get {
                return ResourceManager.GetString("ExtraModifiersIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Fixed automatically..
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Slide&apos;s head, modifier(s) &apos;{0}&apos; should appear after the key number and before the slide type notation..
        /// </summary>
        public static string FixModifiersOnHead {
            get {
                return ResourceManager.GetString("FixModifiersOnHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO:.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token: {0}. Expected: {1}.
        /// </summary>
        public static string InputMismatchException {
            get {
                return ResourceManager.GetString("InputMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser/Generator instances are single-use; do not call Parse or Generate repeatedly! Create a new Parser/Generator for each chart you convert..
        /// </summary>
        public static string InstanceMultipleUsage {
            get {
                return ResourceManager.GetString("InstanceMultipleUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key index (must be 1–8): {0}.
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MA2 statement: after the header section ended, a header-only line appeared again!.
        /// </summary>
        public static string InvalidMA2HeaderSentenceAfterHeader {
            get {
                return ResourceManager.GetString("InvalidMA2HeaderSentenceAfterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized or invalid MA2 statement!.
        /// </summary>
        public static string InvalidMA2Sentence {
            get {
                return ResourceManager.GetString("InvalidMA2Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized MA2 statement; this line was ignored..
        /// </summary>
        public static string InvalidMA2SentenceWarning {
            get {
                return ResourceManager.GetString("InvalidMA2SentenceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid maidata file: no &apos;&amp;&apos; field markers were found..
        /// </summary>
        public static string InvalidMaidataFile {
            get {
                return ResourceManager.GetString("InvalidMaidataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid slide definition: {0}.
        /// </summary>
        public static string InvalidSlide {
            get {
                return ResourceManager.GetString("InvalidSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid touch area specifier: {0}.
        /// </summary>
        public static string InvalidTouchArea {
            get {
                return ResourceManager.GetString("InvalidTouchArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For multi-segment slides with per-segment durations, a wait-time fragment (e.g. {0.5##...}) may only appear on the first segment. Invalid wait-time markers were ignored..
        /// </summary>
        public static string InvalidWaitTime {
            get {
                return ResourceManager.GetString("InvalidWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . The affected note(s) was discarded..
        /// </summary>
        public static string LaxTryfixReminder {
            get {
                return ResourceManager.GetString("LaxTryfixReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized character: {0} (typo?). Ignored..
        /// </summary>
        public static string LexerNoViableAltException {
            get {
                return ResourceManager.GetString("LexerNoViableAltException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized character: {0} (typo?).
        /// </summary>
        public static string LexerNoViableAltExceptionStrict {
            get {
                return ResourceManager.GetString("LexerNoViableAltExceptionStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error: MA2 CN___ (connecting slide) has a non-zero wait time..
        /// </summary>
        public static string MA2CNSlideHasWait {
            get {
                return ResourceManager.GetString("MA2CNSlideHasWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error: MA2 CN___ (connecting slide) has no preceding slide segment!.
        /// </summary>
        public static string MA2CNSlideNoPrevious {
            get {
                return ResourceManager.GetString("MA2CNSlideNoPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This MA2 line has more parameters than required; the extras were ignored..
        /// </summary>
        public static string MA2NoteSentenceTooManyParam {
            get {
                return ResourceManager.GetString("MA2NoteSentenceTooManyParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string MessageAt {
            get {
                return ResourceManager.GetString("MessageAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar time {0:W}.
        /// </summary>
        public static string MessageBar {
            get {
                return ResourceManager.GetString("MessageBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}.
        /// </summary>
        public static string MessageLine {
            get {
                return ResourceManager.GetString("MessageLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parsing &quot;{0}&quot;.
        /// </summary>
        public static string MessageParsing {
            get {
                return ResourceManager.GetString("MessageParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2}s.
        /// </summary>
        public static string MessageTime {
            get {
                return ResourceManager.GetString("MessageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar time {0:W}({1:F2}s).
        /// </summary>
        public static string MessageTimeAndBar {
            get {
                return ResourceManager.GetString("MessageTimeAndBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart has no BPM line; parsing cannot continue!.
        /// </summary>
        public static string NoBPMInMA2 {
            get {
                return ResourceManager.GetString("NoBPMInMA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot be set on Tap or Touch notes..
        /// </summary>
        public static string NoDuration {
            get {
                return ResourceManager.GetString("NoDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart has no notes!.
        /// </summary>
        public static string NoNotesInChart {
            get {
                return ResourceManager.GetString("NoNotesInChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This note is closer than a 384th note to the previous note. MA2 can only represent timing down to 1/384 of a whole note, so these two notes cannot be represented exactly and may be emitted as a yellow EACH pair. If you want a &quot;fake EACH&quot;, use syntax such as &quot;1`2&quot;, or offset the notes by at least one 384th note..
        /// </summary>
        public static string NoteTooNear {
            get {
                return ResourceManager.GetString("NoteTooNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse chart markup: {0}.
        /// </summary>
        public static string NoViableAltException {
            get {
                return ResourceManager.GetString("NoViableAltException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraneous token: {0} (typo?). Ignored..
        /// </summary>
        public static string RecoverInlineExtraneousToken {
            get {
                return ResourceManager.GetString("RecoverInlineExtraneousToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraneous token: {0} (typo?).
        /// </summary>
        public static string RecoverInlineExtraneousTokenStrict {
            get {
                return ResourceManager.GetString("RecoverInlineExtraneousTokenStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing token {1} before {0} (typo?). Inserted automatically..
        /// </summary>
        public static string RecoverInlineMissingToken {
            get {
                return ResourceManager.GetString("RecoverInlineMissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse simai syntax! .
        /// </summary>
        public static string SimaiGrammarFailed {
            get {
                return ResourceManager.GetString("SimaiGrammarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected another Slide head/Tap at the same time and position as this Slide head. This would cause judgement issues in-game. Fixed automatically (removed the redundant Slide head(s)). PS: If you intend same-head Slides, use syntax like &quot;1-2*-3&quot; rather than &quot;1-2/1-3&quot;; the latter triggers this issue..
        /// </summary>
        public static string SimultaneousSlideHead {
            get {
                return ResourceManager.GetString("SimultaneousSlideHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart contains features not supported by MA2 (Break or EX Touch). Those modifiers were ignored..
        /// </summary>
        public static string SpecialTouchIn105 {
            get {
                return ResourceManager.GetString("SpecialTouchIn105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No BPM was specified at the start of the chart! A ({0}) has been inserted automatically at the beginning..
        /// </summary>
        public static string StartNoBpm {
            get {
                return ResourceManager.GetString("StartNoBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This MA2 version is not supported yet. Currently only MA2 1.02–1.05 are supported..
        /// </summary>
        public static string UnsuppoertedMA2Version {
            get {
                return ResourceManager.GetString("UnsuppoertedMA2Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-standard MA2 version encountered: {0}.
        /// </summary>
        public static string WarnNonStdMA2Version {
            get {
                return ResourceManager.GetString("WarnNonStdMA2Version", resourceCulture);
            }
        }
    }
}
